# Generated by Django 6.1.1 on 2026-09-17 10:29

from django.db import migrations

def copy_teacher_links(apps, schema_editor):
    Student = apps.get_model('school', 'Student')
    db_alias = schema_editor.connection.alias

    for student in Student.objects.using(db_alias).all().iterator():
        student.teachers.add(student.teacher_id)

class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_add_student_teachers'),
    ]

    operations = [
        migrations.RunPython(
            copy_teacher_links,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
