# Generated by Django 6.1.1 on 2026-09-17 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_copy_teacher_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
    ]
